Link Atcore-app with atcore
patrickelectric/AtCore-app pull request #4
Opened 2017-09-20 21:07 UTC by sithlord48

Connect button will now connect (needs https://phabricator.kde.org/D7759)

Signed-off-by: Chris Rizzitello <sithlord48@gmail.com>

2017-09-21 00:38 UTC, patrickelectric requested changes
Can you test this on android ?

2017-09-21 00:38 UTC, patrickelectric commented on main.cpp
> +    qmlRegisterType<AtCore>("org.kde.atcore",1,0,"AtCore");
Space after commas.

2017-09-21 00:38 UTC, patrickelectric commented on main.qml
> +                        atcore.initSerial(devText.text,115200`)
Space after comma.
Lost `after 115200.

2017-09-21 11:35 UTC, sithlord48 commented
where is our style file ? 
i adjust these asap
If you can build on android i can test it , i can't build for android atm

2017-09-22 23:36 UTC, patrickelectric commented
I think that would be better to merge this in other branch, I am finishing a better interface, please hold on.

2017-09-23 16:09 UTC, patrickelectric commented
@sithlord48 you have done a merge and not a rebase, please, rebase your branch and remove the merge commit.

2017-09-23 23:46 UTC, patrickelectric commented
@sithlord48 very good, tys.
I'll test here first, and than I will merge it.

2017-09-27 00:48 UTC, patrickelectric commented
Ok, after the new patche merge in atcore master, it was possible to compile it.
As you can see, you have changed some things that broke the gui, please, take a look on it.
![image](https://user-images.githubusercontent.com/1215497/30890622-54453190-a304-11e7-8726-08afba245358.png)

2026-01-22 19:52 UTC, closed without merging